# Defines how the release body is formatted. 
# $CHANGES is where the categorized list will appear.
template: |
  ### Leetcode Solutions — release v$RESOLVED_VERSION
  $CHANGES
  
  **Full Changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION


# These categories match the labels from your labeler.yaml
categories:
  - title: 'Solutions'
    labels:
      - 'solution'
  - title: 'Tooling'
    labels:
      - 'tooling'
  - title: 'Documentation'
    labels:
      - 'documentation'

# Fallback for anything that doesn't match the above
exclude-labels:
  - 'skip-changelog'

replacers:
  - search: '/^## (.*)$/gm'
    replace: '**$1**'